name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build_and_publish_docker_image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/dmr2mongo:${{ github.ref_name }} .

      - name: Push to Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dmr2mongo:${{ github.ref_name }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/dmr2mongo:${{ github.ref_name }} ${{ secrets.DOCKER_USERNAME }}/dmr2mongo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dmr2mongo:latest